// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BlockService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from BlockService.proto</summary>
public static partial class BlockServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for BlockService.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BlockServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJCbG9ja1NlcnZpY2UucHJvdG8iLwoMQmxvY2tNZXNzYWdlEg4KBnN5bmNJ",
          "ZBgBIAEoEhIPCgdibG9ja0lkGAIgASgSYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BlockMessage), global::BlockMessage.Parser, new[]{ "SyncId", "BlockId" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class BlockMessage : pb::IMessage<BlockMessage> {
  private static readonly pb::MessageParser<BlockMessage> _parser = new pb::MessageParser<BlockMessage>(() => new BlockMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<BlockMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BlockServiceReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BlockMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BlockMessage(BlockMessage other) : this() {
    syncId_ = other.syncId_;
    blockId_ = other.blockId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BlockMessage Clone() {
    return new BlockMessage(this);
  }

  /// <summary>Field number for the "syncId" field.</summary>
  public const int SyncIdFieldNumber = 1;
  private long syncId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long SyncId {
    get { return syncId_; }
    set {
      syncId_ = value;
    }
  }

  /// <summary>Field number for the "blockId" field.</summary>
  public const int BlockIdFieldNumber = 2;
  private long blockId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long BlockId {
    get { return blockId_; }
    set {
      blockId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as BlockMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(BlockMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SyncId != other.SyncId) return false;
    if (BlockId != other.BlockId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (SyncId != 0L) hash ^= SyncId.GetHashCode();
    if (BlockId != 0L) hash ^= BlockId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (SyncId != 0L) {
      output.WriteRawTag(8);
      output.WriteSInt64(SyncId);
    }
    if (BlockId != 0L) {
      output.WriteRawTag(16);
      output.WriteSInt64(BlockId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (SyncId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeSInt64Size(SyncId);
    }
    if (BlockId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeSInt64Size(BlockId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(BlockMessage other) {
    if (other == null) {
      return;
    }
    if (other.SyncId != 0L) {
      SyncId = other.SyncId;
    }
    if (other.BlockId != 0L) {
      BlockId = other.BlockId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SyncId = input.ReadSInt64();
          break;
        }
        case 16: {
          BlockId = input.ReadSInt64();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
