// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntityService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from EntityService.proto</summary>
public static partial class EntityServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for EntityService.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EntityServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNFbnRpdHlTZXJ2aWNlLnByb3RvGhJCbG9ja1NlcnZpY2UucHJvdG8aFFNl",
          "c3Npb25TZXJ2aWNlLnByb3RvIiYKEEFsbEVudGl0eU1lc3NhZ2USEgoKc3lu",
          "Y0lkTGlzdBgBIAMoEiJBCg1FbnRpdHlNZXNzYWdlEg4KBnN5bmNJZBgBIAEo",
          "EhIgCglibG9ja0xpc3QYAiADKAsyDS5CbG9ja01lc3NhZ2UyUgoNRW50aXR5",
          "U2VydmljZRJBChlSZXF1ZXN0QWxsRW50aXRpZXNTeW5jSWRzEg8uUmVxdWVz",
          "dE1lc3NhZ2UaES5BbGxFbnRpdHlNZXNzYWdlIgBiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::BlockServiceReflection.Descriptor, global::SessionServiceReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AllEntityMessage), global::AllEntityMessage.Parser, new[]{ "SyncIdList" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EntityMessage), global::EntityMessage.Parser, new[]{ "SyncId", "BlockList" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class AllEntityMessage : pb::IMessage<AllEntityMessage> {
  private static readonly pb::MessageParser<AllEntityMessage> _parser = new pb::MessageParser<AllEntityMessage>(() => new AllEntityMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<AllEntityMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EntityServiceReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AllEntityMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AllEntityMessage(AllEntityMessage other) : this() {
    syncIdList_ = other.syncIdList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AllEntityMessage Clone() {
    return new AllEntityMessage(this);
  }

  /// <summary>Field number for the "syncIdList" field.</summary>
  public const int SyncIdListFieldNumber = 1;
  private static readonly pb::FieldCodec<long> _repeated_syncIdList_codec
      = pb::FieldCodec.ForSInt64(10);
  private readonly pbc::RepeatedField<long> syncIdList_ = new pbc::RepeatedField<long>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<long> SyncIdList {
    get { return syncIdList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as AllEntityMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(AllEntityMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!syncIdList_.Equals(other.syncIdList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= syncIdList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    syncIdList_.WriteTo(output, _repeated_syncIdList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += syncIdList_.CalculateSize(_repeated_syncIdList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(AllEntityMessage other) {
    if (other == null) {
      return;
    }
    syncIdList_.Add(other.syncIdList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 8: {
          syncIdList_.AddEntriesFrom(input, _repeated_syncIdList_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class EntityMessage : pb::IMessage<EntityMessage> {
  private static readonly pb::MessageParser<EntityMessage> _parser = new pb::MessageParser<EntityMessage>(() => new EntityMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<EntityMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EntityServiceReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityMessage(EntityMessage other) : this() {
    syncId_ = other.syncId_;
    blockList_ = other.blockList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EntityMessage Clone() {
    return new EntityMessage(this);
  }

  /// <summary>Field number for the "syncId" field.</summary>
  public const int SyncIdFieldNumber = 1;
  private long syncId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long SyncId {
    get { return syncId_; }
    set {
      syncId_ = value;
    }
  }

  /// <summary>Field number for the "blockList" field.</summary>
  public const int BlockListFieldNumber = 2;
  private static readonly pb::FieldCodec<global::BlockMessage> _repeated_blockList_codec
      = pb::FieldCodec.ForMessage(18, global::BlockMessage.Parser);
  private readonly pbc::RepeatedField<global::BlockMessage> blockList_ = new pbc::RepeatedField<global::BlockMessage>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::BlockMessage> BlockList {
    get { return blockList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as EntityMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(EntityMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SyncId != other.SyncId) return false;
    if(!blockList_.Equals(other.blockList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (SyncId != 0L) hash ^= SyncId.GetHashCode();
    hash ^= blockList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (SyncId != 0L) {
      output.WriteRawTag(8);
      output.WriteSInt64(SyncId);
    }
    blockList_.WriteTo(output, _repeated_blockList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (SyncId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeSInt64Size(SyncId);
    }
    size += blockList_.CalculateSize(_repeated_blockList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(EntityMessage other) {
    if (other == null) {
      return;
    }
    if (other.SyncId != 0L) {
      SyncId = other.SyncId;
    }
    blockList_.Add(other.blockList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SyncId = input.ReadSInt64();
          break;
        }
        case 18: {
          blockList_.AddEntriesFrom(input, _repeated_blockList_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
