// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntityService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class EntityService
{
  static readonly string __ServiceName = "EntityService";

  static readonly grpc::Marshaller<global::RequestMessage> __Marshaller_RequestMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RequestMessage.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::AllEntityMessage> __Marshaller_AllEntityMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AllEntityMessage.Parser.ParseFrom);

  static readonly grpc::Method<global::RequestMessage, global::AllEntityMessage> __Method_RequestAllEntitiesSyncIds = new grpc::Method<global::RequestMessage, global::AllEntityMessage>(
      grpc::MethodType.Unary,
      __ServiceName,
      "RequestAllEntitiesSyncIds",
      __Marshaller_RequestMessage,
      __Marshaller_AllEntityMessage);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::EntityServiceReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of EntityService</summary>
  [grpc::BindServiceMethod(typeof(EntityService), "BindService")]
  public abstract partial class EntityServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::AllEntityMessage> RequestAllEntitiesSyncIds(global::RequestMessage request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for EntityService</summary>
  public partial class EntityServiceClient : grpc::ClientBase<EntityServiceClient>
  {
    /// <summary>Creates a new client for EntityService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public EntityServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for EntityService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public EntityServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected EntityServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected EntityServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::AllEntityMessage RequestAllEntitiesSyncIds(global::RequestMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RequestAllEntitiesSyncIds(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::AllEntityMessage RequestAllEntitiesSyncIds(global::RequestMessage request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_RequestAllEntitiesSyncIds, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::AllEntityMessage> RequestAllEntitiesSyncIdsAsync(global::RequestMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RequestAllEntitiesSyncIdsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::AllEntityMessage> RequestAllEntitiesSyncIdsAsync(global::RequestMessage request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_RequestAllEntitiesSyncIds, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override EntityServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new EntityServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(EntityServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_RequestAllEntitiesSyncIds, serviceImpl.RequestAllEntitiesSyncIds).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, EntityServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_RequestAllEntitiesSyncIds, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RequestMessage, global::AllEntityMessage>(serviceImpl.RequestAllEntitiesSyncIds));
  }

}
#endregion
