// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SessionService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SessionService.proto</summary>
public static partial class SessionServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for SessionService.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SessionServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRTZXNzaW9uU2VydmljZS5wcm90byI2ChhDb25uZWN0aW9uUmVxdWVzdE1l",
          "c3NhZ2USDAoEZ3VpZBgBIAEoCRIMCgRuYW1lGAIgASgJInoKGUNvbm5lY3Rp",
          "b25SZXNwb25zZU1lc3NhZ2USLQoMcmVzcG9uc2VUeXBlGAEgASgOMhcuQ29u",
          "bmVjdGlvblJlc3BvbnNlVHlwZRIVCg1yZXNwb25zZVRva2VuGAIgASgJEhcK",
          "D3Jlc3BvbnNlTWVzc2FnZRgDIAEoCSIfCg5SZXF1ZXN0TWVzc2FnZRINCgV0",
          "b2tlbhgBIAEoCSIHCgVFbXB0eSpJChZDb25uZWN0aW9uUmVzcG9uc2VUeXBl",
          "EgsKB1JFRlVTRUQQABIOCgpDT05ORUNUSU9OEAESEgoOTkVXX0NPTk5FQ1RJ",
          "T04QAjKKAQoOU2Vzc2lvblNlcnZpY2USTAoRUmVxdWVzdENvbm5lY3Rpb24S",
          "GS5Db25uZWN0aW9uUmVxdWVzdE1lc3NhZ2UaGi5Db25uZWN0aW9uUmVzcG9u",
          "c2VNZXNzYWdlIgASKgoNRGlzY29ubmVjdGlvbhIPLlJlcXVlc3RNZXNzYWdl",
          "GgYuRW1wdHkiAGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ConnectionResponseType), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ConnectionRequestMessage), global::ConnectionRequestMessage.Parser, new[]{ "Guid", "Name" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ConnectionResponseMessage), global::ConnectionResponseMessage.Parser, new[]{ "ResponseType", "ResponseToken", "ResponseMessage" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RequestMessage), global::RequestMessage.Parser, new[]{ "Token" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Empty), global::Empty.Parser, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum ConnectionResponseType {
  [pbr::OriginalName("REFUSED")] Refused = 0,
  [pbr::OriginalName("CONNECTION")] Connection = 1,
  [pbr::OriginalName("NEW_CONNECTION")] NewConnection = 2,
}

#endregion

#region Messages
public sealed partial class ConnectionRequestMessage : pb::IMessage<ConnectionRequestMessage> {
  private static readonly pb::MessageParser<ConnectionRequestMessage> _parser = new pb::MessageParser<ConnectionRequestMessage>(() => new ConnectionRequestMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ConnectionRequestMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SessionServiceReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ConnectionRequestMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ConnectionRequestMessage(ConnectionRequestMessage other) : this() {
    guid_ = other.guid_;
    name_ = other.name_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ConnectionRequestMessage Clone() {
    return new ConnectionRequestMessage(this);
  }

  /// <summary>Field number for the "guid" field.</summary>
  public const int GuidFieldNumber = 1;
  private string guid_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Guid {
    get { return guid_; }
    set {
      guid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ConnectionRequestMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ConnectionRequestMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Guid != other.Guid) return false;
    if (Name != other.Name) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Guid.Length != 0) hash ^= Guid.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Guid.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Guid);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Guid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Guid);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ConnectionRequestMessage other) {
    if (other == null) {
      return;
    }
    if (other.Guid.Length != 0) {
      Guid = other.Guid;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Guid = input.ReadString();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class ConnectionResponseMessage : pb::IMessage<ConnectionResponseMessage> {
  private static readonly pb::MessageParser<ConnectionResponseMessage> _parser = new pb::MessageParser<ConnectionResponseMessage>(() => new ConnectionResponseMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ConnectionResponseMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SessionServiceReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ConnectionResponseMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ConnectionResponseMessage(ConnectionResponseMessage other) : this() {
    responseType_ = other.responseType_;
    responseToken_ = other.responseToken_;
    responseMessage_ = other.responseMessage_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ConnectionResponseMessage Clone() {
    return new ConnectionResponseMessage(this);
  }

  /// <summary>Field number for the "responseType" field.</summary>
  public const int ResponseTypeFieldNumber = 1;
  private global::ConnectionResponseType responseType_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ConnectionResponseType ResponseType {
    get { return responseType_; }
    set {
      responseType_ = value;
    }
  }

  /// <summary>Field number for the "responseToken" field.</summary>
  public const int ResponseTokenFieldNumber = 2;
  private string responseToken_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ResponseToken {
    get { return responseToken_; }
    set {
      responseToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "responseMessage" field.</summary>
  public const int ResponseMessageFieldNumber = 3;
  private string responseMessage_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ResponseMessage {
    get { return responseMessage_; }
    set {
      responseMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ConnectionResponseMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ConnectionResponseMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ResponseType != other.ResponseType) return false;
    if (ResponseToken != other.ResponseToken) return false;
    if (ResponseMessage != other.ResponseMessage) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ResponseType != 0) hash ^= ResponseType.GetHashCode();
    if (ResponseToken.Length != 0) hash ^= ResponseToken.GetHashCode();
    if (ResponseMessage.Length != 0) hash ^= ResponseMessage.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ResponseType != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) ResponseType);
    }
    if (ResponseToken.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ResponseToken);
    }
    if (ResponseMessage.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ResponseMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ResponseType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseType);
    }
    if (ResponseToken.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ResponseToken);
    }
    if (ResponseMessage.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ResponseMessage);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ConnectionResponseMessage other) {
    if (other == null) {
      return;
    }
    if (other.ResponseType != 0) {
      ResponseType = other.ResponseType;
    }
    if (other.ResponseToken.Length != 0) {
      ResponseToken = other.ResponseToken;
    }
    if (other.ResponseMessage.Length != 0) {
      ResponseMessage = other.ResponseMessage;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ResponseType = (global::ConnectionResponseType) input.ReadEnum();
          break;
        }
        case 18: {
          ResponseToken = input.ReadString();
          break;
        }
        case 26: {
          ResponseMessage = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class RequestMessage : pb::IMessage<RequestMessage> {
  private static readonly pb::MessageParser<RequestMessage> _parser = new pb::MessageParser<RequestMessage>(() => new RequestMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RequestMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SessionServiceReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RequestMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RequestMessage(RequestMessage other) : this() {
    token_ = other.token_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RequestMessage Clone() {
    return new RequestMessage(this);
  }

  /// <summary>Field number for the "token" field.</summary>
  public const int TokenFieldNumber = 1;
  private string token_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Token {
    get { return token_; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RequestMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RequestMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Token != other.Token) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Token.Length != 0) hash ^= Token.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Token.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Token);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Token.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RequestMessage other) {
    if (other == null) {
      return;
    }
    if (other.Token.Length != 0) {
      Token = other.Token;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Token = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class Empty : pb::IMessage<Empty> {
  private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Empty> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SessionServiceReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Empty() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Empty(Empty other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Empty Clone() {
    return new Empty(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Empty);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Empty other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Empty other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  }

}

#endregion


#endregion Designer generated code
